version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: botdb
      MYSQL_USER: botuser
      MYSQL_PASSWORD: botpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - .env
    command: ["python", "-m", "src.bot"]
    # Jeśli chcesz mieć hot-reload lokalnie, możesz odkomentować:
    # volumes:
    #   - .:/app

volumes:
  mysql-data:
